### ISSUE TITLE
ADAL should enable use of system creds

### ISSUE THREAD

**Issue by onovotny** [microsoft/artifacts-credprovider#127] opened 2019-09-08 16:06 UTC
ADAL currently uses PromptBehavior.Always:
https://github.com/microsoft/artifacts-credprovider/blob/master/CredentialProvider.Microsoft/CredentialProviders/Vsts/AdalTokenProvider.cs#L85

Instead, it should use PromptBehavior.SelectAccount, which enables the user to select workplace joined/AAD joined accounts and remove the need to enter in a password again.

**Comment by satbai** [comment] 2020-02-05 23:03
I'm going to close this issue because it looks like it's a duplicate of https://github.com/microsoft/artifacts-credprovider/issues/161

**Closed by satbai** 2020-02-05 23:03 UTC
Labels: enhancement
