### ISSUE TITLE
How to set CanShowDialog from MSBuild?

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/artifacts-credprovider#37] opened 2018-10-09 01:48 UTC
Hi @satbai I'm using the credprovider from MSBuild, and even though I pass `/p:NugetInteractive=true` the `CanShowDialog` is still set to false:

```
IsNonInteractive: False, CanShowDialog: False
```

It looks like there is no way to thread through the setting to the task from MSBuild?

**Comment by nkolev92** [comment] 2018-10-09 18:34
@KirillOsenkov There is no way to do that. 

By design MSBuild will never allow plugins to pop-up a dialog. 
This was a decision made jointly between NuGet and @jeffkl and @AndyGerlicher. 

We thought it's important that the host (msbuild,dotnet.exe) makes the decision on what the experience will be like.

**Comment by KirillOsenkov** [comment] 2018-10-09 23:12
I'm taken by surprise that this was a deliberate decision ;)

What is happening is you're pausing the build and prompting for user interaction via device flow, and then fail after a certain timeout if user didn't auth. So in a way it is already interactive, just not showing a dialog. 

But the unfortunate UX of this is the user launched the build, specified /p:nugetInteractive=true, fully expecting a dialog to pop up, and switched away to reading Twitter, waiting for that dialog. The device flow prompt was buried in a sea of random output, and after I get tired of Twitter I switch back to MSBuild only to find out that the auth failed for some unknown reason.

I certainly understand that MSBuild showing dialogs sounds nonsensical, however I'd rather have that than the device flow experience, honestly. Two improvements come to mind:

 1. Highlight the device flow prompt using a bright console color, surround with ASCII frames and make sure it's the last thing in the MSBuild output console, and not buried in random output. 

 2. Allow the user to pass a property to switch to the auth dialog if they so choose. You can keep device flow as default, if it is more discoverable. But there needs to be an option at least.

**Comment by jeffkl** [comment] 2018-10-10 04:04
I personally expect all prompts to come from the command window itself.  I've had command-line tools pop up dialogs and sometimes they appear behind my windows which is bad.  They also cannot be made modal so I can bring the command window back to focus and not know that it has popped up this other unrelated window.

I think the biggest reason we didn't want to pop up a dialog is because MSBuild is cross platform and we wouldn't be able to open a consistent looking dialog on the various platforms.  This means that `MSBuild.exe` would pop up a dialog while `dotnet msbuild` would not, even on the same machine.  Even if we made MSBuild pop up a dialog on Windows only, I think it would be bad if I had a different experience on a Mac or Linux machine. The device flow experience is at least consistent across all platforms.  When running inside Visual Studio, you get a dialog as you'd expect since you're running in a UI.

Currently, MSBuild has no concept of "prompts".  The messages are simply logged as high importance messages.  We could potentially add another logging level to make it a different color.  If we don't care about the color, we could change the overall look of the prompt inside this credential provider.  I'd definitely be behind a change to the text of the prompt as we just released it and its a good time to revisit if people have feedback.

**Comment by nkolev92** [comment] 2018-10-10 04:39
There's also a similar issue regarding the visibility of the messaged raised on NuGet's repo. https://github.com/NuGet/Home/issues/7364

So that is something that we can definitely brainstorm. 
As far as the client is concerned, currently that is a generic log message, so the easiest thing would be for the plugin to add some pretty print around it.

**Comment by satbai** [comment] 2018-10-10 16:07
Adding bright colored logging around the device flow prompt is a good idea. I've added it to our back log.

**Comment by nkolev92** [comment] 2018-10-10 16:39
@satbai 

The plugin itself does not have control over the color schema of the logging since the nuget tools write the output. 

You can however change the content of the log message to make it pop a bit more. 

Potentially you could log at a warning level that would change the color of the output, but that's a misuse.

**Comment by nkolev92** [comment] 2018-10-10 17:38
As a side-note, there's been requests/suggestions that device flow should be the default every time. 
//cc @loic-sharma

**Comment by KirillOsenkov** [comment] 2018-10-10 18:50
@jeffkl Fall back to device flow

**Comment by alexmullans** [comment] 2019-01-25 18:09
Tagging this as duplicate of NuGet/Home#7364.

**Comment by satbai** [comment] 2019-01-25 18:18
The latest version of the credential provider has some additional attention tracking print around the device flow prompt. https://github.com/Microsoft/artifacts-credprovider/releases

**Comment by alexmullans** [comment] 2019-01-29 18:51
Closing this as the duplicate issue is closed and we've improved the visibility of the device flow request.

**Closed by alexmullans** 2019-01-29 18:51 UTC
Labels: duplicate, enhancement
