### ISSUE TITLE
Can't restore with NuGet.exe (error running the CredentialProvider)

### ISSUE THREAD

**Issue by Diogomrol** [microsoft/artifacts-credprovider#114] opened 2019-07-30 10:11 UTC
Hi,

I am trying to use the CredentialProvider to authenticate with a feed in Azure Artifacts, but I can't get it to work with nuget.exe restore.

I have the CredentialProvider in a custom folder and set the NUGET_CREDENTIALPROVIDERS_PATH env var to that same place.

However, when I attemp to run NuGet restore, it keeps failing with 401 (Unauthorized).

I tried to pass the switch -verbosity detailed to nuget.exe, and I get the followin stack trace:

`Restoring NuGet package Node.js.x86.0.10.36.
WARNING: The credential plugin model used by 'C:\svn\trunkrepo\ServiceStudio\..\Commons\ThirdParty\AzureCredentialsProvider\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe' is deprecated. Please contact the provider of the plugin for an alternative. More information about the recommended plugin model can be found at 'https://aka.ms/nuget-cross-platform-authentication-plugin'.
CredentialProvider.Microsoft: Unhandled Exception: PowerArgs.ValidationArgException: detailed is not a valid value for type LogLevel, options are Debug, Verbose, Information, Minimal, Warning, Error
CredentialProvider.Microsoft:    at PowerArgs.ArgRevivers.ReviveEnum(Type t, String value, Boolean ignoreCase)
CredentialProvider.Microsoft:    at PowerArgs.CommandLineArgument.Revive(String commandLineValue)
CredentialProvider.Microsoft:    at PowerArgs.CommandLineArgument.Populate(HookContext context)
CredentialProvider.Microsoft:    at PowerArgs.CommandLineArgument.PopulateArguments(List`1 arguments, HookContext context)
CredentialProvider.Microsoft:    at PowerArgs.Args.ParseInternal(CommandLineArgumentsDefinition definition, String[] input)
CredentialProvider.Microsoft:    at PowerArgs.Args.<>c__DisplayClass13_0.<ParseAction>b__0()
CredentialProvider.Microsoft:    at PowerArgs.Args.Execute[T](Func`1 argsProcessingCode)
CredentialProvider.Microsoft:    at PowerArgs.Args.ParseAction(CommandLineArgumentsDefinition definition, String[] args)
CredentialProvider.Microsoft:    at PowerArgs.Args.ParseAction(Type t, String[] args)
CredentialProvider.Microsoft:    at PowerArgs.Args.Parse(Type t, String[] args)
CredentialProvider.Microsoft:    at PowerArgs.Args.Parse[T](String[] args)
CredentialProvider.Microsoft:    at PowerArgs.Args.<>c__DisplayClass22_0`1.<ParseAsync>b__0()
CredentialProvider.Microsoft:    at System.Threading.Tasks.Task`1.InnerInvoke()
CredentialProvider.Microsoft:    at System.Threading.Tasks.Task.Execute()
CredentialProvider.Microsoft: --- End of stack trace from previous location where exception was thrown ---
CredentialProvider.Microsoft:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
CredentialProvider.Microsoft:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
CredentialProvider.Microsoft:    at NuGetCredentialProvider.Program.<Main>d__11.MoveNext() in E:\A\_work\857\s\CredentialProvider.Microsoft\Program.cs:line 63
CredentialProvider.Microsoft: --- End of stack trace from previous location where exception was thrown ---
CredentialProvider.Microsoft:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
CredentialProvider.Microsoft:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
CredentialProvider.Microsoft:    at NuGetCredentialProvider.Program.<Main>(String[] args)`

Can I get some help to understand what's going on? It looks like when I build using MSBuild (without calling nuget.exe directly) it works, but I can't get it to work with nuget.exe.

Best Regards,
Diogo Oliveira

**Comment by Diogomrol** [comment] 2019-07-30 12:29
Well it looks like this specific error happens because I passed the -verbosity argument to NuGet.exe call and it also calls the CrendentialProvider with that.

But the problem is still here: if I do not use the -verbosity argument the warning about credential plugin model being deprecated still shows up and then I get a 401 Unauthorized

**Comment by Diogomrol** [comment] 2019-07-30 12:37
So, more news on this.

If I try to call the CredentialProvider directly it seems to work, using this command line:

`CredentialProvider.Microsoft.exe -uri https://pkgs.dev.azure.com/<project>/_packaging/<feed>/nuget/v3/index.json -nonInteractive`

I actually get a response with a username and a password.

However, through nuget.exe, I am getting the following error:

> WARNING: The credential plugin model used by 'C:\svn\trunkrepo\ServiceStudio\..\Commons\ThirdParty\AzureCredentialsProvider\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe' is deprecated. Please contact the provider of the plugin for an alternative. More information about the recommended plugin model can be found at 'https://aka.ms/nuget-cross-platform-authentication-plugin'.
Credential plugin C:\svn\trunkrepo\ServiceStudio\..\Commons\ThirdParty\AzureCredentialsProvider\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe returned Success with an unreadable payload.

**Comment by nkolev92** [comment] 2019-07-31 19:05
NUGET_CREDENTIALPROVIDERS_PATH is used for plugins supporting the old plugin model: https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-exe-credential-providers. 

This is a V2 style provider: 

https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-plugins#plugin-installation-and-discovery

Basically, don't use the environment variable. If you already have the plugin in the netfx folder, it should pick it up automatically.

**Comment by zarenner** [comment] 2019-08-22 18:41
Closing as not a bug. @diogomrol please let us know if you're still having issues, but hopefully Nikolche's guidance above helped.

**Closed by zarenner** 2019-08-22 18:41 UTC
